# This is a development Django container
version: '3.8'

services:

  redis_service:
    container_name: redis_container
    image: redis:7.0.11-alpine

  flower_service:
    container_name: flower_container
    image: mher/flower
    ports:
      - 5555:5555
    env_file:
      - ./django/.env.celery_dev

  django_with_celery_site:
    container_name: django_with_celery_site_container
    build:
      context: ./django
      dockerfile: ./DockerFile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/django
    ports:
      - 8005:8000
    # environment:
    #   - DEBUG=1
    #   - SECRET_KEY=
    #   - ALLOWED_HOSTS=localhost, 127.0.0.1
    env_file:
      - ./django/.env.django_dev
      - ./django/.env.celery_dev
    depends_on:
      - redis_service

  celery_worker_with_django:
    container_name: calery_worker_with_django_container
    build:
      context: ./django
      dockerfile: ./DockerFile
    # This is not running a website
    # command: python manage.py runserver 0.0.0.0:8000
    # We run Celery here instead
    command: celery --app=celery_worker worker --hostname=celery_with_django@%h -l INFO
    volumes:
      - ./django:/django
    # ports:
    #   - 8005:8000
    env_file:
      - ./django/.env.django_dev
      - ./django/.env.celery_dev
    depends_on:
      - redis_service

  celery_worker_non_django:
    container_name: celery_worker_non_django_container
    build:
      context: ./other_non_django_code
      dockerfile: ./DockerFile
    command: /bin/sh -c "pwd && ls -lR && celery --app=celery_worker.non_django_celery worker --hostname=celery_non_django@%h -l INFO"
    volumes:
      - ./other_non_django_code:/other_non_django_code
    env_file:
      - ./django/.env.celery_dev
      # This could also be a dedicated environment file
      # - ./other_non_django_code/.env.celery_dev
    depends_on:
      - redis_service
