# This is a development Django container
version: '3.8'

services:

  redis_service:
    container_name: redis_container
    image: redis:7.0.11-alpine

  django_with_celery_site:
    container_name: django_with_celery_site_container
    build:
      context: ./django
      dockerfile: ./DockerFile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/django
    ports:
      - 8005:8000
    # environment:
    #   - DEBUG=1
    #   - SECRET_KEY=
    #   - ALLOWED_HOSTS=localhost, 127.0.0.1
    env_file:
      - ./django/.env.django_dev
      - ./django/.env.celery_dev
    depends_on:
      - redis_service

  django_with_celery_worker:
    container_name: django_with_celery_worker_container
    build:
      context: ./django
      dockerfile: ./DockerFile
    # This is not running a website
    # command: python manage.py runserver 0.0.0.0:8000
    # We run Celery here instead
    command: celery --app=celery_worker worker -l INFO
    volumes:
      - ./django:/django
    # ports:
    #   - 8005:8000
    env_file:
      - ./django/.env.django_dev
      - ./django/.env.celery_dev
    depends_on:
      - redis_service

  non_django_celery_worker:
    container_name: non_django_celery_worker_container
    build:
      context: ./other_non_django_code
      dockerfile: ./DockerFile
    command: /bin/sh -c "pwd && ls -lR && celery --app=celery_worker.non_django_celery worker -l INFO"
    volumes:
      - ./other_non_django_code:/other_non_django_code
    env_file:
      - ./other_non_django_code/.env.celery_dev
    depends_on:
      - redis_service
