FROM python:3.11.4-alpine

WORKDIR /other_non_django_code

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONBUFFERED 1

COPY requirements.txt requirements.txt

RUN python -m pip install --upgrade pip && \
    python -m pip install -r requirements.txt

# Zander copies the whole directory, 
# but we have a volume for that purpose and this works.
# You do need to copy the requirements.txt  for the 
# build to work.
